const data = {
  products: [
    {
      name: "Nike Slim shirt",
      slug: "nike-slim-shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      name: "Addida Fit shirt",
      slug: "Addida-Fit-shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 250,
      countInStock: 20,
      brand: "Addidas",
      rating: 4.0,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      name: "Nike Slim Pant",
      slug: "nike-slim-Pant",
      category: "Pants",
      image: "/images/p3.jpg",
      price: 25,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "high quality Pant",
    },
    {
      name: "Addida Fit Pant",
      slug: "Addida-Fit-Pant",
      category: "Pant",
      image: "/images/p4.jpg",
      price: 65,
      countInStock: 5,
      brand: "Addidas",
      rating: 4.5,
      numReviews: 10,
      description: "high quality Pant",
    },
  ],
};
export default data;
